name: CI/CD

on: [push, workflow_dispatch]

jobs:
  Installing-Dependencies:
    runs-on: windows-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3  

      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18 

      - name: Installing dependencies
        run: npm ci

      - name: Install PM2 globally
        run: |
          npm install -g pm2
          pm2 update

      - name: Starting Your Node.js App
        run: pm2 start app.js



        

  # deploy:
  #   runs-on: windows-latest    
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
      
  #     - name: Set up SSH keys
  #       run: |
  #         ssh-keyscan -H ${{secrets.REMOTE_IP}} >> ~/.ssh/known_hosts  # Add your server's IP
  #         ssh -i ${{secrets.SSH_PRIVATE_KEY}}  user@${{ secrets.REMOTE_IP }} "cd C:\Users\MetaorangeAdmin\Desktop\cicd && git pull origin main && npm install && pm2 restart app.js" 
    
  deploys:
    runs-on: ubuntu-latest    
    steps:
       - name: Checkout code
         uses: actions/checkout@v3
        
       - name: Install dependencies  # If needed
         run: |
                  # Add commands to install dependencies here
        
       - name: Deploy code to remote server
         run: |
          scp -r ./your_code user@${{ secrets.REMOTE_IP }}:C:/Users/MetaorangeAdmin/Desktop/cicd/AssessmentEngine-Backend
        
              # Add any additional steps for server setup or configuration here
        
       - name: Verify deployment
         run: |
                  # Add commands to verify the deployment
                  # For example, you can run tests or other checks here
        